defmodule Hapesire.Repo.Migrations.AddQuotesEn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:quotes_en, primary_key: false) do
      add :author, :text
      add :text, :text, null: false, primary_key: true
    end
  end

  def down do
    drop table(:quotes_en)
  end
end